# A ServiceAccount defines the identity a Pod uses when calling
# the Kubernetes API from inside the cluster.
# For most FEATURE work you rarely touch it
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      # Links to a service account by name
      serviceAccountName: my-sa
      containers:
        - name: app
          image: nginx
