apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MY_VAR: aG9sYSE=
  BYE_VAR: YWRpb3Mh

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: app
      image: nginx:1.25-alpine
      command: ["sh", "-c", "echo $MY_VAR and $BYE_VAR && sleep 3600"]
      envFrom:
        - secretRef:
            name: my-secret
