apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-all
data:
  MY_VAR: "hola!"
  BYE_VAR: "adios!"
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: app
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "MY_VAR=$(cat /config/MY_VAR), BYE_VAR=$(cat /config/BYE_VAR)"
          sleep 3600
      volumeMounts:
        - name: config-vol
          mountPath: /config
  volumes:
    - name: config-vol
      configMap:
        name: cm-all
