apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  clusterIP: None        # headless for stable DNS
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app              # prefix -> app-0, app-1...
spec:
  serviceName: myapp
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: main
          image: nginx
          volumeMounts:
            - name: scratch
              mountPath: /data          # ephemeral
      volumes:
        - name: scratch
          emptyDir: {}                   # loses data on restart
