apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-a-html
data:
  index.html: |
    <html><body><h1>Hello from Pod A</h1></body></html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-b-html
data:
  index.html: |
    <html><body><h1>Hello from Pod BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB</h1></body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      pod: a
  template:
    metadata:
      labels:
        app: nginx
        pod: a
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: pod-a-html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      pod: b
  template:
    metadata:
      labels:
        app: nginx
        pod: b
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: pod-b-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
